{
"1":"Inwoners totaal",
"2":"Inwoners 0 tot 15 jaar",
"3":"Inwoners 15 tot 25 jaar",
"4":"Inwoners 25 tot 45 jaar",
"5":"Inwoners 45 tot 65 jaar",
"6":"Inwoners 65 jaar en ouder",
"7":"Bevolkingsdichtheid",
"8":"Verandering inwonertal 2000-2010",
"9":"Eenpersoonshuishoudens",
"10":"Huishoudens zonder kinderen",
"11":"Huishoudens met kinderen",
"12":"Autochtonen (%)",
"13":"Niet-westerse allochtonen (%)",
"14":"Westerse allochtonen (%)",
"15":"Aantal inkomensontvangers",
"16":"Inkomen per ontvanger",
"17":"Inwoners met laag inkomen (%)",
"18":"Inwoners met hoog inkomen (%)",
"19":"Huishoudens met laag inkomen (%)",
"20":"Huishoudens met hoog inkomen (%)",
"21":"Huishoudens sociaal minimin (%)",
"22":"Woningen",
"23":"Woning WOZ-waarde",
"24":"Agrarische bedrijven",
"25":"Industrie (%)",
"26":"Commerciële dienstverlening (%)",
"27":"Niet-commerciële dienstverlening (%)",
"28":"Huisartsenpraktijk",
"29":"Huisartsenpost",
"30":"Ziekenhuis, excl. buitenpolikliniek",
"31":"Kinderdagverblijf",
"32":"Buitenschoolse opvang",
"33":"Basisonderwijs",
"34":"VMBO onderwijs",
"35":"HAVO/VWO onderwijs",
"36":"Grote supermarkt",
"37":"Ov. dagelijkse levensmiddelen",
"38":"Omgevingsadressendichtheid",
"selected":"1"
}